# Generated by Django 2.2 on 2019-12-12 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteB', models.CharField(max_length=50)),
                ('quoteA', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GoEnigma.User')),
            ],
        ),
    ]
