# Generated by Django 2.2 on 2019-12-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoEnigma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='authorA',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='authorB',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
